import { Center } from '@chakra-ui/react';
import Head from 'next/head';
import CallToActionWithVideo from '../components/CTA/memedCTA';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Section from '../components/Section';

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Lombeira</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header />
      </header>

      <main>Contato</main>

      <Footer />
    </div>
  );
}
